### ISSUE TITLE
iOS userland daemons support

### ISSUE THREAD

**Issue by professorUnknown** [DerekSelander/yacd#2]
Retracted

**Comment by professorUnknown** [comment]
For continued discussion dm me at https://twitter.com/anonymouspriva3

**Comment by professorUnknown** [comment]
@DerekSelander

**Comment by DerekSelander** [comment]
PRs are welcome

But you can grab this straight from an IPSW

I am not going to dm you on Twitter for a feature you want me to do for you.

**Comment by professorUnknown** [comment]
Thank you for your time and the advice Ok you want a reason why to dm me I know a person with a iOS 14 sandbox escape but you probably already know I will close the issue since it isn’t relevant .

**Comment by DerekSelander** [comment]
@professorUnknown If true, I really appreciate you taking the time to contact me. But that is highly valued information and you don’t know me. Although I would not use it for financial gain (submitting to Apple or somewhere else), you don’t know who would take advantage of this information. For that, I must respectfully decline 

Thanks

**Comment by professorUnknown** [comment]
Also sorry for wasting your time I will delete all my comments also I said too much.

**Comment by DerekSelander** [comment]
@professorUnknown  Understood.  Thanks again for reaching out

**Comment by professorUnknown** [comment]
Your app is amazing. I don’t have too much of details about it but I am just who will introduce you the owner of it. To be honest I don’t know how to code so you will put into greater use than me but I understand your humility and respect it. Don’t thank me thank yourself!
