### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by Sinterc** [DerekSelander/yacd#3]
Assertion failed: (err == KERN_SUCCESS), function _copyin_string, file /Users/.../lorgnette.m, line 567
on iOS 12.4.1
May I ask how to solve this problem

**Comment by DerekSelander** [comment]
I'll need a stack trace and ideally the app you were inspecting

**Comment by everettjf** [comment]
Hi, I got the same error on iOS12.4
![image](https://user-images.githubusercontent.com/1665109/93367891-b639d580-f87f-11ea-9d9c-e825d52fc684.png)
