### ISSUE TITLE
iPhone XS Max iOS 13.1.1 When I open it, it's blank

### ISSUE THREAD

**Issue by LiJingBiao** [DerekSelander/yacd#9]
![IMG_6599B2B1F8BA-1](https://user-images.githubusercontent.com/5698458/94108244-8a1ae780-fe71-11ea-8645-86d409670e1f.jpeg)
![IMG_E17A726DD67D-1](https://user-images.githubusercontent.com/5698458/94108254-8dae6e80-fe71-11ea-9523-362fa68ddcdc.jpeg)

**Comment by Apibug** [comment]
点右上角的刷新图标

**Comment by LiJingBiao** [comment]
> 点右上角的刷新图标

LSApplicationWorkspace这个类在iOS11以后就获取不到App里面的应用了
